baseURL = 'https://anohbajhd.github.io/'
title = 'Anohba Jehad'
theme = "blowfish"
languageCode = "en-us"
defaultContentLanguage = "en"

enableRobotsTXT = true
enableEmoji = true
summaryLength = 0

buildDrafts = false
buildFuture = false

[pagination]
  pagerSize = 100

[taxonomies]
  tag = "tags"
  category = "categories"
  author = "authors"
  series = "series"

[outputs]
  home = ["HTML", "RSS", "JSON"]

[module]
  [module.hugoVersion]
    extended = true
    min = "0.141.0"
