colorScheme = "blowfish"
defaultAppearance = "dark"
autoSwitchAppearance = true

enableSearch = true
enableCodeCopy = true

mainSections = ["posts"]

[header]
  layout = "basic"

[footer]
  showMenu = true
  showCopyright = true
  showThemeAttribution = true
  showAppearanceSwitcher = true
  showScrollToTop = true

[homepage]
  layout = "profile"
  homepageImage = "pf.jpeg"
  showRecent = true
  showRecentItems = 6
  showMoreLink = true
  showMoreLinkDest = "/posts/"
  cardView = true
  cardViewScreenWidth = false

[article]
  showDate = true
  showDateUpdated = false
  showAuthor = true
  showBreadcrumbs = true
  showDraftLabel = true
  showHeadingAnchors = true
  showPagination = true
  showReadingTime = true
  showTableOfContents = true
  showTaxonomies = true
  showWordCount = true
  showZenMode = false

[list]
  showBreadcrumbs = true
  showSummary = true
  groupByYear = true
  cardView = true
  cardViewScreenWidth = false

[taxonomy]
  showTermCount = true

[sitemap]
  excludedKinds = ["taxonomy", "term"]
